name: voqula
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.0.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^6.0.2
  image_picker: ^1.2.0
  firebase_storage: ^13.0.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.9.3
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/cover/cover_app.jpg"
    min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/cover/
    - assets/books/
    - assets/books/best_selling/
    - assets/books/best_selling/author/
    - assets/books/popular_books/
    - assets/popular/
    - assets/profile/